### ISSUE TITLE
Unknown directory type causes deserialization failure again

### ISSUE THREAD

**Issue by singron** [workos/workos-kotlin#162]
Same issue as https://github.com/workos/workos-kotlin/issues/97 but with "rippling scim v2.0".

I'll reiterate here that we don't even look at this field and we would be very happy if it was just a String and not an enum.

**Comment by maxdeviant** [comment]
Hey @singron,

We just released [v2.11.0](https://github.com/workos/workos-kotlin/releases/tag/v2.11.0) of the Kotlin SDK that addresses this issue.

We're going to take a look and see what we can do to better account for new directory types that aren't present in the enum.

**Comment by singron** [comment]
Thank you!
