### ISSUE TITLE
listUsers not taking any options?

### ISSUE THREAD

**Issue by johnwards** [workos/workos-kotlin#231]
Hey, I'm new to Java/Kotlin (I'm a node guy) but I have to make a change to a Java project so I'm stumbling my way through this.

I've got this code:
```
ListUsersOptions options = new ListUsersOptions(email, authConfigProperties.getOrgId());
Users workOSUsers = userManagementApi.listUsers(options);
```

But when I HTTP inspect the call to the API, it isn't passing the params on to the API so I get all users.

Now I've done a little bit of debugging, but I'm getting a bit lost in the world of Java. But from what I can tell you've got some code in the get func that looks like this:

```
if (config?.params != null) {
      for ((key, value) in config.params.entries) {
        uri.addParameter(key, value)
      }
    }
```
    
 But the ListUsersOptions object doesn't have any params set. I don't think the build code is doing anything?
 
 ```
return workos.get(
      "/user_management/users",
      Users::class.java,
      RequestConfig.builder().data(options ?: ListUsersOptions()).build()
    )
```

**Comment by PaulAsjes** [comment]
Hey there, can you let me know which version of the SDK you're currently using?

**Comment by johnwards** [comment]
Hey, yes, sorry. `'com.workos:workos:3.1.0-beta.user-management5'`

Need the user management stuff so on the beta channel as I don't think that's out yet.

**Comment by PaulAsjes** [comment]
Thanks for the report, looks like there's an issue with all the list endpoints, hence why it's a beta :)

We'll get this looked at and fixed soon!

**Comment by PaulAsjes** [comment]
Hey there, sorry for the wait but this should be fixed in the new beta release: https://github.com/workos/workos-kotlin/releases/tag/v3.1.0-beta.user-management6

I'm closing this for now, but please feel free to reopen if you encounter any other issues!
